<?php

namespace Ice\DoctrineMockOfVeritasClientBundle\Exception;

use Exception;

class MethodNotImplementedException extends \RuntimeException
{
    public function __construct($message = "", $code = 0, Exception $previous = null)
    {
        if (!$message) {
            $callers=debug_backtrace();
            $message = sprintf("Method %s::%s is not supported in testing", $callers[1]['class'], $callers[1]['function']);
        }

        parent::__construct($message, $code, $previous); // TODO: Change the autogenerated stub
    }
}
